---

- name: configure login banner
  hosts: ios
  connection: network_cil

  tasks:
   - name: configure login banner
     ios_banner:
      banner: motd
       text: |
        new login banner
        second line
       state: present
